version: '3.7'

services:
  run-up-admin:
    container_name: run-up-admin
    restart: always
    build: .
    command: yarn start
    environment:
      PORT: 80
      HTTPS: true
      VIRTUAL_HOST: admin.zorp.co
      LETSENCRYPT_HOST: admin.zorp.co
      LETSENCRYPT_EMAIL: hello@jackallen.me
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
